apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 30444
  type: NodePort # or LoadBalancer, depending on your requirements
